# Google Cloud Build configuration for CI/CD pipeline
# This file automates testing, building, and deployment to Cloud Run

steps:
  # Step 1: Install dependencies and run tests
  - name: 'python:3.11-slim'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        pip install --no-cache-dir -r requirements.txt
        echo "Running pytest with coverage..."
        pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=xml
        echo "Tests completed successfully!"
    env:
      - 'ENVIRONMENT=testing'
      - 'DATABASE_URL=sqlite:///./test.db'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/user-management-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/user-management-api:latest'
      - '.'
    waitFor: ['run-tests']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/user-management-api:$COMMIT_SHA'
    waitFor: ['build-image']

  # Step 4: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/user-management-api:latest'
    waitFor: ['push-image']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'user-management-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/user-management-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,APP_NAME=User Management API'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'
    waitFor: ['push-latest']

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/user-management-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/user-management-api:latest'

# Build configuration options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for the entire build process (20 minutes)
timeout: '1200s'

# Tags for organizing builds
tags: ['user-management-api', 'fastapi', 'cloud-run']

